export type BuiltInSocialNetwork = {
  id: string
  label: string
  route: `/${string}`
  url: string
  icon: string
  color: string
  tileColor?: string
  customIcon?: 'threads' | 'snapchat' | 'nextdoor'
  onboarding: boolean
  defaultSelected: boolean
}

export const builtInSocialNetworks: BuiltInSocialNetwork[] = [
  {
    id: 'twitter',
    label: 'Twitter / X',
    route: '/twitter',
    url: 'https://x.com',
    icon: 'pi pi-twitter',
    color: '#1DA1F2',
    tileColor: '#000000',
    onboarding: true,
    defaultSelected: true,
  },
  {
    id: 'facebook',
    label: 'Facebook',
    route: '/facebook',
    url: 'https://facebook.com',
    icon: 'pi pi-facebook',
    color: '#1877F2',
    onboarding: true,
    defaultSelected: true,
  },
  {
    id: 'instagram',
    label: 'Instagram',
    route: '/instagram',
    url: 'https://instagram.com',
    icon: 'pi pi-instagram',
    color: '#E4405F',
    tileColor: 'linear-gradient(135deg, #f09433, #e6683c, #dc2743, #cc2366, #bc1888)',
    onboarding: true,
    defaultSelected: true,
  },
  {
    id: 'linkedin',
    label: 'LinkedIn',
    route: '/linkedin',
    url: 'https://linkedin.com',
    icon: 'pi pi-linkedin',
    color: '#0A66C2',
    onboarding: true,
    defaultSelected: true,
  },
  {
    id: 'tiktok',
    label: 'TikTok',
    route: '/tiktok',
    url: 'https://tiktok.com',
    icon: 'pi pi-tiktok',
    color: '#000000',
    tileColor: '#010101',
    onboarding: true,
    defaultSelected: true,
  },
  {
    id: 'threads',
    label: 'Threads',
    route: '/threads',
    url: 'https://threads.net',
    icon: 'pi pi-at',
    customIcon: 'threads',
    color: '#000000',
    onboarding: true,
    defaultSelected: false,
  },
  {
    id: 'discord',
    label: 'Discord',
    route: '/discord',
    url: 'https://discord.com/app',
    icon: 'pi pi-discord',
    color: '#5865F2',
    onboarding: true,
    defaultSelected: false,
  },
  {
    id: 'reddit',
    label: 'Reddit',
    route: '/reddit',
    url: 'https://reddit.com',
    icon: 'pi pi-reddit',
    color: '#FF4500',
    onboarding: true,
    defaultSelected: false,
  },
  {
    id: 'snapchat',
    label: 'Snapchat',
    route: '/snapchat',
    url: 'https://web.snapchat.com',
    icon: 'pi pi-camera',
    customIcon: 'snapchat',
    color: '#FFFC00',
    onboarding: true,
    defaultSelected: false,
  },
  {
    id: 'quora',
    label: 'Quora',
    route: '/quora',
    url: 'https://www.quora.com',
    icon: 'pi pi-question-circle',
    color: '#B92B27',
    onboarding: true,
    defaultSelected: false,
  },
  {
    id: 'pinterest',
    label: 'Pinterest',
    route: '/pinterest',
    url: 'https://www.pinterest.com',
    icon: 'pi pi-pinterest',
    color: '#BD081C',
    tileColor: '#E60023',
    onboarding: true,
    defaultSelected: false,
  },
  {
    id: 'telegram',
    label: 'Telegram',
    route: '/telegram',
    url: 'https://web.telegram.org',
    icon: 'pi pi-telegram',
    color: '#26A5E4',
    tileColor: '#0088cc',
    onboarding: true,
    defaultSelected: false,
  },
  {
    id: 'nextdoor',
    label: 'Nextdoor',
    route: '/nextdoor',
    url: 'https://nextdoor.com',
    icon: 'pi pi-map-marker',
    customIcon: 'nextdoor',
    color: '#8ED500',
    onboarding: true,
    defaultSelected: false,
  },
]
